name: Run tests and publish report

on: workflow_dispatch

jobs:
  test:
    # где заускаем
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tags: [ full_test, min_success_test, negative_test ]

    # что делаем
    steps:
      # выкачиваем репозиторий
      - uses: actions/checkout@v3
      # настраиваем java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: Xotabu4/selenoid-github-action@v2
      - run: |
          # Запуск тестов в зависимости от выбранного тэга
          case "${{ matrix.tags }}" in
            full_test)
              ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub -Dtags=full_test
              ;;
            min_success_test)
              ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub -Dtags=min_success_test
              ;;
            negative_test)
              ./gradlew clean test -Dselenide.remote=http://localhost:4444/wd/hub -Dtags=negative_test
              ;;
            *)
              echo "Invalid tag provided"
              exit 1
              ;;
          esac

      # скачиваем историю тестов
      - uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages
      # генерируем отчет
      - uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: build/allure-results
          allure_report: allure-report
          allure_history: allure-history
      # публикуем отчет
      - uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history